In [7]:
import torch
x = torch.randn(2, 3)
x2 = torch.randn(2, 3)
a_x = [x,x2]
print(a_x)
y = torch.cat(a_x,1)
print(y)

[tensor([[-0.8286,  1.7147,  0.8366],
        [ 0.4602,  2.8007,  1.8288]]), tensor([[-0.9708, -0.2743, -0.6511],
        [-1.1926, -1.1932, -1.1061]])]
tensor([[-0.8286,  1.7147,  0.8366, -0.9708, -0.2743, -0.6511],
        [ 0.4602,  2.8007,  1.8288, -1.1926, -1.1932, -1.1061]])


In [14]:
x = torch.randn(3)
print(x)
print(x.unsqueeze(1))
print(x.unsqueeze(0))

tensor([ 0.8145,  0.5932, -1.5644])
tensor([[ 0.8145],
        [ 0.5932],
        [-1.5644]])
tensor([[ 0.8145,  0.5932, -1.5644]])


In [30]:
x = torch.randn(3)
y = x.repeat(2)
z = y.unsqueeze(0)
w = z.repeat(3,3)
w_b = z.repeat(3,2)
w_a = z.repeat(3,1)
# print(x)
# print(y)
# print(z)
print(w)
print(w_b)
print(w_a)
# repeat(input_length).unsqueeze(0).repeat(batch_size, 1)

tensor([[-0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707,
         -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,
          0.7707, -0.7061],
        [-0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707,
         -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,
          0.7707, -0.7061],
        [-0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707,
         -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,
          0.7707, -0.7061]])
tensor([[-0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707,
         -0.7061, -0.3046,  0.7707, -0.7061],
        [-0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707,
         -0.7061, -0.3046,  0.7707, -0.7061],
        [-0.3046,  0.7707, -0.7061, -0.3046,  0.7707, -0.7061, -0.3046,  0.7707,
         -0.7061, -0.3046,  0.7707, -0.7061]])
tensor([[-0.3046,  0.7707, -0.7061, -0.3046,  0